# Generated by Django 5.1.6 on 2025-05-09 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('volume', models.IntegerField(default=0)),
                ('high_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='newsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('published_at', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'unique_together': {('title', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(blank=True, max_length=64, null=True)),
                ('notification_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('none', 'None')], default='daily', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_trigger', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insidertrading.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('stocks', models.ManyToManyField(through='insidertrading.WatchedStock', to='insidertrading.stock')),
            ],
        ),
        migrations.AddField(
            model_name='watchedstock',
            name='watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insidertrading.watchlist'),
        ),
        migrations.AlterUniqueTogether(
            name='watchedstock',
            unique_together={('watchlist', 'stock')},
        ),
    ]
