# Generated by Django 5.1.6 on 2025-03-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insidertrading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='high_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='low_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
