# Generated by Django 5.1.6 on 2025-02-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insidertrading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='company_name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
