# Generated by Django 5.1.6 on 2025-05-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insidertrading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
