# Generated by Django 5.1.6 on 2025-05-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insidertrading', '0002_alter_newsarticle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
