# Generated by Django 5.1.6 on 2025-05-17 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insidertrading', '0003_profile_blocked_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedstock',
            name='added_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='watchedstock',
            name='added_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='watchedstock',
            name='amount_held',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
