# Generated by Django 5.1.6 on 2025-04-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insidertrading', '0004_stock_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='change_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
