# Generated by Django 5.1.6 on 2025-05-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insidertrading', '0004_watchedstock_added_at_watchedstock_added_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
