# Generated by Django 5.1.6 on 2025-04-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insidertrading', '0005_stock_change_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='change_percentage',
        ),
        migrations.AddField(
            model_name='stock',
            name='high_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='low_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
