# Generated by Django 5.1.6 on 2025-05-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insidertrading', '0005_stock_industry_alter_stock_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedstock',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
